# Generated by Django 5.2.2 on 2025-09-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
        (
            'provider',
            '0002_rename_display_name_provider_name_provider_platform_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spotify_provider',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='members',
                to='provider.provider',
            ),
        ),
        migrations.AddField(
            model_name='member',
            name='spotify_proxy_account',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_members',
                to='provider.providerproxyaccount',
            ),
        ),
    ]
