# Generated by Django 5.2.2 on 2025-10-01 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_member_spotify_provider_member_spotify_proxy_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='spotify_proxy_account',
        ),
    ]
