"kind": "pipeline"
"name": "walrus-migration-check"
"node":
  "repo": "Lab3-Spotify-walrus"
"steps":
- "commands":
  - "pip install -r requirements.txt || exit 1"
  - "python manage.py check || exit 1"
  - "python manage.py makemigrations --dry-run --check"
  "environment":
    "DJANGO_SECRET_KEY": "MIGRATION_CHECK_PIPELINE_SUPER_SECRET"
  "image": "python:3.10.13-slim"
  "name": "migration-dry-run"
"trigger":
  "event":
  - "pull_request"
"type": "kubernetes"
---
"kind": "pipeline"
"name": "walrus-test"
"node":
  "repo": "Lab3-Spotify-walrus"
"services":
- "environment":
    "POSTGRES_DB": "walrus-test"
    "POSTGRES_PASSWORD": "walrus-test"
    "POSTGRES_USER": "walrus-test"
  "image": "postgres:14-alpine"
  "name": "walrus-test-db"
- "image": "redis:7.4.2"
  "name": "walrus-test-redis"
"steps":
- "commands":
  - "pip install -r requirements.txt || exit 1"
  - "python manage.py test || exit 1"
  "environment":
    "DJANGO_SECRET_KEY": "TEST_PIPELINE_SUPER_SECRET"
    "ENV": "test"
    "POSTGRES_DB": "walrus-test"
    "POSTGRES_HOST": "walrus-test-db"
    "POSTGRES_PASSWORD": "walrus-test"
    "POSTGRES_PORT": "5432"
    "POSTGRES_USER": "walrus-test"
    "REDIS_HOST": "rwalrus-test-redis"
    "REDIS_PORT": "6379"
  "image": "python:3.10.13-slim"
  "name": "install-and-test"
"trigger":
  "branch":
  - "master"
  "event":
  - "push"
"type": "kubernetes"
---
"kind": "pipeline"
"name": "walrus-deploy"
"node":
  "repo": "Lab3-Spotify-walrus"
"steps":
- "image": "plugins/docker"
  "name": "build and push docker image"
  "settings":
    "password":
      "from_secret": "DOCKER_PASSWORD_pony"
    "repo": "popopopony/walrus"
    "tags":
    - "latest"
    - "${DRONE_COMMIT_SHA}"
    "username":
      "from_secret": "DOCKER_USERNAME_pony"
- "commands":
  - "kubectl set image deployment/walrus walrus=popopopony/walrus:${DRONE_COMMIT_SHA} --namespace=walrus || exit 1"
  - "kubectl rollout status deployment/walrus --namespace=walrus || exit 1"
  - "echo Deployment success!"
  "image": "sinlead/drone-kubectl"
  "name": "deploy to k8s"
  "settings":
    "kubernetes_cert":
      "from_secret": "K8S_CA"
    "kubernetes_server":
      "from_secret": "K8S_SERVER"
    "kubernetes_token":
      "from_secret": "K8S_TOKEN"
    "namespace": "walrus"
    "startTimeout": 240
"trigger":
  "branch":
  - "master"
  "event":
  - "push"
"type": "kubernetes"
