"kind": "pipeline"
"name": "walrus-migration-check"
"node":
  "repo": "Lab3-Spotify-walrus"
"steps":
- "commands":
  - "pip install poetry==1.6.1 poetry-plugin-export"
  - "poetry export -f requirements.txt --without-hashes -o requirements.txt"
  - "pip install -r requirements.txt || exit 1"
  - "python manage.py check || exit 1"
  - "python manage.py makemigrations --dry-run --check"
  "environment":
    "DJANGO_SECRET_KEY": "MIGRATION_CHECK_PIPELINE_SUPER_SECRET"
  "image": "python:3.10.13-slim"
  "name": "migration-dry-run"
"trigger":
  "event":
  - "pull_request"
"type": "kubernetes"
---
"kind": "pipeline"
"name": "walrus-test"
"node":
  "repo": "Lab3-Spotify-walrus"
"services":
- "environment":
    "POSTGRES_DB": "walrus-test"
    "POSTGRES_PASSWORD": "walrus-test"
    "POSTGRES_USER": "walrus-test"
  "image": "postgres:14-alpine"
  "name": "walrus-test-db"
- "image": "redis:7.4.2"
  "name": "walrus-test-redis"
"steps":
- "commands":
  - "pip install poetry==1.6.1 poetry-plugin-export"
  - "poetry export -f requirements.txt --without-hashes -o requirements.txt"
  - "pip install -r requirements.txt || exit 1"
  - "python manage.py test || exit 1"
  "environment":
    "DJANGO_SECRET_KEY": "TEST_PIPELINE_SUPER_SECRET"
    "ENV": "test"
    "POSTGRES_DB": "walrus-test"
    "POSTGRES_HOST": "walrus-test-db"
    "POSTGRES_PASSWORD": "walrus-test"
    "POSTGRES_PORT": "5432"
    "POSTGRES_USER": "walrus-test"
    "REDIS_HOST": "walrus-test-redis"
    "REDIS_PORT": "6379"
  "image": "python:3.10.13-slim"
  "name": "install-and-test"
"trigger":
  "branch":
  - "master"
  "event":
  - "push"
"type": "kubernetes"
---
"kind": "pipeline"
"name": "walrus-deploy"
"node":
  "repo": "Lab3-Spotify-walrus"
"steps":
- "image": "plugins/docker"
  "name": "build and push docker image"
  "settings":
    "build_args":
    - "BUILDKIT_INLINE_CACHE=1"
    "buildkit": true
    "cache_from":
    - "lislab3morris/walrus:latest"
    "password":
      "from_secret": "docker-password"
    "repo": "lislab3morris/walrus"
    "tags":
    - "latest"
    - "${DRONE_COMMIT_SHA}"
    "username":
      "from_secret": "docker-username"
- "commands":
  - "kubectl set image deployment/walrus walrus=lislab3morris/walrus:${DRONE_COMMIT_SHA} --namespace=walrus || exit 1"
  - "kubectl set image deployment/walrus-celery-playlog walrus-celery-playlog=lislab3morris/walrus:${DRONE_COMMIT_SHA} --namespace=walrus || exit 1"
  - "kubectl set image deployment/walrus-celery-beat walrus-celery-beat=lislab3morris/walrus:${DRONE_COMMIT_SHA} --namespace=walrus || exit 1"
  - "kubectl rollout status deployment/walrus --namespace=walrus || exit 1"
  - "kubectl rollout status deployment/walrus-celery-playlog --namespace=walrus || exit 1"
  - "kubectl rollout status deployment/walrus-celery-beat --namespace=walrus || exit 1"
  - "echo Deployment success!"
  "image": "bitnami/kubectl"
  "name": "deploy to k8s"
"trigger":
  "branch":
  - "master"
  "event":
  - "push"
"type": "kubernetes"
---
"get":
  "name": "value"
  "path": "docker-username"
"kind": "secret"
"name": "docker-username"
---
"get":
  "name": "value"
  "path": "docker-password"
"kind": "secret"
"name": "docker-password"
