# Generated by Django 5.2.2 on 2025-06-29 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('provider', '0001_initial'),
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreHistory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('count', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'genre',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='genre_histories',
                        to='track.genre',
                    ),
                ),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='genre_histories',
                        to='account.member',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='genre_histories',
                        to='provider.provider',
                    ),
                ),
            ],
            options={
                'unique_together': {('member', 'genre', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='TrackHistoryPlayLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('played_at', models.DateTimeField()),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='track_play_logs',
                        to='account.member',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='track_play_logs',
                        to='provider.provider',
                    ),
                ),
                (
                    'track',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='track_play_logs',
                        to='track.track',
                    ),
                ),
            ],
            options={
                'unique_together': {('member', 'track', 'provider', 'played_at')},
            },
        ),
    ]
