# Generated by Django 5.2.7 on 2025-10-23 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_experimentgroup_alter_member_experiment_group'),
        ('listening_profile', '0001_initial'),
        ('provider', '0004_remove_providerproxyaccount_is_available_and_more'),
        ('track', '0002_track_isrc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackHistoryPlayLog',
            new_name='HistoryPlayLog',
        ),
        migrations.DeleteModel(
            name='GenreHistory',
        ),
    ]
