# Generated by Django 5.2.7 on 2025-11-01 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'listening_profile',
            '0002_rename_trackhistoryplaylog_historyplaylog_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPlayLogContext',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('playlist', 'Playlist'),
                            ('album', 'Album'),
                            ('artist', 'Artist'),
                        ],
                        max_length=50,
                    ),
                ),
                ('external_id', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['type', 'external_id'],
                        name='listening_p_type_7eb723_idx',
                    )
                ],
                'unique_together': {('type', 'external_id')},
            },
        ),
        migrations.AddField(
            model_name='historyplaylog',
            name='context',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='play_logs',
                to='listening_profile.historyplaylogcontext',
            ),
        ),
    ]
