# Generated by Django 5.2.2 on 2025-09-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='display_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='provider',
            name='platform',
            field=models.CharField(
                choices=[('spotify', 'Spotify')], default='spotify', max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='api_handler',
            field=models.CharField(help_text='API Handler import path', max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='auth_handler',
            field=models.CharField(
                help_text='Auth Handler import path', max_length=255
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ProviderProxyAccount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='provider.provider',
                    ),
                ),
            ],
            options={
                'unique_together': {('provider', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProviderProxyAccountAPIToken',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('_access_token', models.TextField(db_column='access_token')),
                (
                    '_refresh_token',
                    models.TextField(blank=True, db_column='refresh_token', null=True),
                ),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'proxy_account',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='api_token',
                        to='provider.providerproxyaccount',
                    ),
                ),
            ],
        ),
    ]
