# Generated by Django 5.2.2 on 2025-09-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'provider',
            '0002_rename_display_name_provider_name_provider_platform_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='providerproxyaccount',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
