# Generated by Django 5.2.2 on 2025-10-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_remove_member_spotify_proxy_account'),
        ('provider', '0003_providerproxyaccount_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerproxyaccount',
            name='is_available',
        ),
        migrations.AddField(
            model_name='providerproxyaccount',
            name='current_member',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='proxy_accounts',
                to='account.member',
            ),
        ),
    ]
