# Generated by Django 5.2.7 on 2025-10-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='isrc',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
