# Generated by Django 5.2.7 on 2025-10-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('track', '0002_track_isrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='isrc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
