# Generated by Django 5.2.7 on 2025-10-24 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('track', '0003_alter_track_isrc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clip',
        ),
    ]
