# Generated by Django 5.2.7 on 2025-11-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('track', '0004_delete_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
