name: Update ClickUp Task Status on PR Open

on:
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  update_clickup:
    runs-on: ubuntu-latest

    steps:
      # 1. 取得 PR 本文，擷取所有 CU-xxxxxxxxx，並去掉前綴後合併成逗號分隔的列表
      - name: Extract ClickUp Task IDs
        id: extract
        run: |
          body="${{ github.event.pull_request.body }}"
          # 擷取 CU-XXXXXXXXX 並去掉 CU- 前綴
          tasks=$(echo "$body" \
            | grep -oE 'CU-[A-Za-z0-9]{9}' \
            | sed 's/^CU-//' \
            | sort -u \
            | paste -sd ',' -)
          echo "tasks=$tasks" >> $GITHUB_OUTPUT

      # 2. 如果有擷取到任務 ID，就依序呼叫 API 更新狀態
      - name: Update ClickUp Tasks
        if: steps.extract.outputs.tasks != ''
        env:
          API_TOKEN: ${{ secrets.CLICKUP_API_TOKEN }}
          TASK_IDS: ${{ steps.extract.outputs.tasks }}
        run: |
          IFS=',' read -ra IDS <<< "$TASK_IDS"
          for ID in "${IDS[@]}"; do
            echo "→ Updating task $ID to “pr reviewing”"
            curl --silent --fail -X PUT "https://api.clickup.com/api/v2/task/$ID" \
              -H "Authorization: $API_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{"status":"pr reviewing"}' \
              && echo "✔ $ID updated" \
              || echo "✖ failed to update $ID"
          done
