# Generated by Django 5.2.7 on 2025-10-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('account', '0004_experimentgroup_alter_member_experiment_group'),
        ('track', '0002_track_isrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'external_id',
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('experiment', 'Experiment'),
                            ('discover_weekly', 'Discover Weekly'),
                            ('member_favorite', 'Member Favorite'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'length_type',
                    models.CharField(
                        blank=True,
                        choices=[('short', 'Short'), ('long', 'Long')],
                        db_index=True,
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    'favorite_track_position_type',
                    models.CharField(
                        blank=True,
                        choices=[('edge', 'Edge'), ('middle', 'Middle')],
                        db_index=True,
                        max_length=30,
                        null=True,
                    ),
                ),
                ('description', models.TextField(blank=True, null=True)),
                ('satisfaction_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='playlists',
                        to='account.member',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('order', models.IntegerField()),
                ('is_familiar', models.BooleanField(default=False)),
                ('satisfaction_score', models.IntegerField(blank=True, null=True)),
                ('splendid_score', models.IntegerField(blank=True, null=True)),
                ('is_ever_listened', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'playlist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='playlist_tracks',
                        to='playlist.playlist',
                    ),
                ),
                (
                    'track',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='playlist_tracks',
                        to='track.track',
                    ),
                ),
            ],
            options={
                'ordering': ['playlist', 'order'],
                'unique_together': {('playlist', 'track')},
            },
        ),
    ]
