# Generated by Django 5.2.7 on 2025-10-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'ordering': ['playlist', '-created_at', 'order']},
        ),
        migrations.RemoveField(
            model_name='playlisttrack',
            name='is_ever_listened',
        ),
        migrations.RemoveField(
            model_name='playlisttrack',
            name='is_familiar',
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='type',
            field=models.CharField(
                choices=[
                    ('experiment', 'Experiment'),
                    ('member_top', 'Member Top'),
                    ('discover_weekly', 'DIscover Weekly'),
                    ('member_favorite', 'Member Favorite'),
                    ('member_recommendation', 'Member Recommendation'),
                ],
                max_length=50,
            ),
        ),
    ]
