# Generated by Django 5.2.7 on 2025-10-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('playlist', '0002_alter_playlisttrack_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='type',
            field=models.CharField(
                choices=[
                    ('experiment', 'Experiment'),
                    ('discover_weekly', 'DIscover Weekly'),
                    ('member_favorite', 'Member Favorite'),
                ],
                max_length=50,
            ),
        ),
    ]
