# Generated by Django 5.2.7 on 2025-10-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('playlist', '0004_playlist_experiment_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisttrack',
            name='is_ever_listened',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
